stages:
  - test
  - build
  - deploy

test_app:
  stage: test
  image: node:latest
  script:
    - npm install
    - npm test
  only:
    - branche_de_test

build_app:
  stage: build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  before_script:
    - apk add --no-cache docker-compose
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker-compose -f docker-compose.yml build
  only:
    - branche_de_test

deploy_app:
  stage: deploy
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  before_script:
    - apk add --no-cache docker-compose
    - which docker-compose || (echo "docker-compose not found" && false)
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker-compose -f docker-compose.yml up -d
  only:
    - branche_de_test

